name: Build Mac

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      working-directory: ${{github.workspace}}
      run: cl /W4 /EHsc gif-h-demo.cpp
    - name: test
      run: ./gif-h-demo.exe
    - name: Upload test
      uses: actions/upload-artifact@v4
      with:
        name: test-gif
        path: ./MyGif.gif
