name: Build Win

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      working-directory: ${{github.workspace}}
      run: |
        ${VS_INST_PATH} = & "${env:ProgramFiles(x86)}/Microsoft Visual Studio/Installer/vswhere.exe" -latest -property installationPath
        Write-Output "  <-> VS Install Path: ${VS_INST_PATH}"
        Import-Module ${VS_INST_PATH}/Common7/Tools/Microsoft.VisualStudio.DevShell.dll
        Enter-VsDevShell -VsInstallPath ${VS_INST_PATH} -SkipAutomaticLocation -DevCmdArguments '-arch=${{matrix.config.arch}} -no_logo'
        cl /W4 /EHsc gif-h-demo.cpp
    - name: test
      run: ./gif-h-demo.exe
    - name: Upload test
      uses: actions/upload-artifact@v4
      with:
        name: test-gif
        path: ./MyGif.gif
